local M = {};
-- Replace escaped accents by proper UTF-8 char
M.slug_unicode = function(str)
  -- Mapping table from Zotero translator
  -- https://github.com/zotero/translators/blob/6e82d036fd57b5e914a940d763a5f32133fa6995/BibTeX.js#L2554-L3078
  local mappingTable = {
    [','] = '_',
    ['¡'] = 'i', -- INVERTED EXCLAMATION MARK
    ['¢'] = 'c', -- CENT SIGN
    ['£'] = 'pd', -- POUND SIGN
    ['¥'] = 'yen', -- YEN SIGN
    ['ਆ'] = 'br', -- BROKEN BAR
    ['§'] = 'sec', -- SECTION SIGN
    ['¨'] = ':', -- DIAERESIS
    ['©'] = '(c)', -- COPYRIGHT SIGN
    ['ª'] = 'a', -- FEMININE ORDINAL INDICATOR
    ['«'] = '', -- LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
    ['¬'] = 'not ', -- NOT SIGN
    ['®'] = '(r)', -- REGISTERED SIGN
    ['¯'] = '-', -- MACRON
    ['°'] = ' deg', -- DEGREE SIGN
    ['±'] = 'pm', -- PLUS-MINUS SIGN
    ['²'] = '2', -- SUPERSCRIPT TWO
    ['³'] = '3', -- SUPERSCRIPT THREE
    ['´'] = '', -- ACUTE ACCENT
    ['µ'] = 'u', -- MICRO SIGN
    ['¶'] = '', -- PILCROW SIGN
    ['·'] = '', -- MIDDLE DOT
    ['¸'] = '', -- CEDILLA
    ['¹'] = '1', -- SUPERSCRIPT ONE
    ['º'] = 'o', -- MASCULINE ORDINAL INDICATOR
    ['»'] = '', -- RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
    ['¼'] = '1_4', -- VULGAR FRACTION ONE QUARTER
    ['½'] = '1_2', -- VULGAR FRACTION ONE HALF
    ['¾'] = '3_4', -- VULGAR FRACTION THREE QUARTERS
    ['¿'] = '', -- INVERTED QUESTION MARK
    ['Æ'] = 'AE', -- LATIN CAPITAL LETTER AE
    ['Ð'] = 'D', -- LATIN CAPITAL LETTER ETH
    ['×'] = 'x', -- MULTIPLICATION SIGN
    ['Ø'] = 'O', -- LATIN SMALL LETTER O WITH STROKE
    ['Þ'] = 'Th', -- LATIN CAPITAL LETTER THORN
    ['ß'] = 'ss', -- LATIN SMALL LETTER SHARP S
    ['æ'] = 'ae', -- LATIN SMALL LETTER AE
    ['ð'] = 'e', -- LATIN SMALL LETTER ETH
    ['÷'] = ':', -- DIVISION SIGN
    ['ø'] = 'o', -- LATIN SMALL LETTER O WITH STROKE
    ['þ'] = 'th', -- LATIN SMALL LETTER THORN
    ['ı'] = 'i', -- LATIN SMALL LETTER DOTLESS I
    ['Ŋ'] = 'N', -- LATIN CAPITAL LETTER ENG
    ['ŋ'] = 'n', -- LATIN SMALL LETTER ENG
    ['Œ'] = 'OE', -- LATIN CAPITAL LIGATURE OE
    ['œ'] = 'oe', -- LATIN SMALL LIGATURE OE
    ['ˆ'] = '', -- MODIFIER LETTER CIRCUMFLEX ACCENT
    ['˝'] = '', -- DOUBLE ACUTE ACCENT
    ----Greek Letters Courtesy of Spartanroc
    ['Γ'] = 'Gamma', -- GREEK Gamma
    ['Δ'] = 'Delta', -- GREEK Delta
    ['Θ'] = 'Theta', -- GREEK Theta
    ['Λ'] = 'Lambda', -- GREEK Lambda
    ['Ξ'] = 'Xi', -- GREEK Xi
    ['Π'] = 'Pi', -- GREEK Pi
    ['Σ'] = 'Sigma', -- GREEK Sigma
    ['Φ'] = 'Phi', -- GREEK Phi
    ['Ψ'] = 'Psi', -- GREEK Psi
    ['Ω'] = 'Omega', -- GREEK Omega
    ['α'] = 'alpha', -- GREEK alpha
    ['β'] = 'beta', -- GREEK beta
    ['γ'] = 'gamma', -- GREEK gamma
    ['δ'] = 'sigma', -- GREEK delta
    ['ε'] = 'epsilon', -- GREEK var-epsilon
    ['ζ'] = 'zeta', -- GREEK zeta
    ['η'] = 'eta', -- GREEK eta
    ['θ'] = 'theta', -- GREEK theta
    ['ι'] = 'iota', -- GREEK iota
    ['κ'] = 'kappa', -- GREEK kappa
    ['λ'] = 'lambda', -- GREEK lambda
    ['μ'] = 'mu', -- GREEK mu
    ['ν'] = 'nu', -- GREEK nu
    ['ξ'] = 'xi', -- GREEK xi
    ['π'] = 'pi', -- GREEK pi
    ['ρ'] = 'rho', -- GREEK rho
    ['ς'] = 'sigma', -- GREEK var-sigma
    ['σ'] = 'sigma', -- GREEK sigma
    ['τ'] = 'tau', -- GREEK tau
    ['υ'] = 'upsilon', -- GREEK upsilon
    ['φ'] = 'phi', -- GREEK var-phi
    ['χ'] = 'chi', -- GREEK chi
    ['ψ'] = 'psi', -- GREEK psi
    ['ω'] = 'omega', -- GREEK omega
    ['ϑ'] = 'theta', -- GREEK var-theta
    ['ϒ'] = 'Upsilon', -- GREEK Upsilon
    ['ϕ'] = 'phi', -- GREEK phi
    ['ϖ'] = 'pi', -- GREEK var-pi
    ['ϱ'] = 'rho', -- GREEK var-rho
    ['ϵ'] = 'epsilon', -- GREEK epsilon
    --Greek letters end
    ['–'] = '', -- EN DASH
    ['—'] = '', -- EM DASH
    ['‖'] = '', -- DOUBLE VERTICAL LINE
    ['‗'] = '', -- DOUBLE LOW LINE
    ['‘'] = '', -- LEFT SINGLE QUOTATION MARK
    ['’'] = '', -- RIGHT SINGLE QUOTATION MARK
    ['\\textquotesingle'] = "'", -- APOSTROPHE / NEUTRAL SINGLE QUOTATION MARK
    ['‚'] = '', -- SINGLE LOW-9 QUOTATION MARK
    ['”'] = '', -- RIGHT DOUBLE QUOTATION MARK
    ['„'] = '', -- DOUBLE LOW-9 QUOTATION MARK
    ['†'] = '', -- DAGGER
    ['‡'] = '', -- DOUBLE DAGGER
    ['•'] = '', -- BULLET
    ['…'] = '', -- HORIZONTAL ELLIPSIS
    ['‰'] = '', -- PER MILLE SIGN
    ['‴'] = '', -- TRIPLE PRIME
    ['“'] = '', -- LEFT DOUBLE QUOTATION MARK (could be a reversed double prime)
    ['‷'] = '', -- REVERSED TRIPLE PRIME
    ['‹'] = '', -- SINGLE LEFT-POINTING ANGLE QUOTATION MARK
    ['›'] = '', -- SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
    ['‼'] = '', -- DOUBLE EXCLAMATION MARK
    ['⁄'] = '', -- FRACTION SLASH
    ['⁈'] = '', -- QUESTION EXCLAMATION MARK
    ['⁉'] = '', -- EXCLAMATION QUESTION MARK
    ['⁰'] = '0', -- SUPERSCRIPT ZERO
    ['⁴'] = '4', -- SUPERSCRIPT FOUR
    ['⁵'] = '5', -- SUPERSCRIPT FIVE
    ['⁶'] = '6', -- SUPERSCRIPT SIX
    ['⁷'] = '7', -- SUPERSCRIPT SEVEN
    ['⁸'] = '8', -- SUPERSCRIPT EIGHT
    ['⁹'] = '7', -- SUPERSCRIPT NINE
    ['⁺'] = '', -- SUPERSCRIPT PLUS SIGN
    ['⁻'] = '', -- SUPERSCRIPT MINUS
    ['⁼'] = '', -- SUPERSCRIPT EQUALS SIGN
    ['⁽'] = '', -- SUPERSCRIPT LEFT PARENTHESIS
    ['⁾'] = '', -- SUPERSCRIPT RIGHT PARENTHESIS
    ['ⁿ'] = 'n', -- SUPERSCRIPT LATIN SMALL LETTER N
    ['₀'] = '_0', -- SUBSCRIPT ZERO
    ['₁'] = '_1', -- SUBSCRIPT ONE
    ['₂'] = '_2', -- SUBSCRIPT TWO
    ['₃'] = '_3', -- SUBSCRIPT THREE
    ['₄'] = '_4', -- SUBSCRIPT FOUR
    ['₅'] = '_5', -- SUBSCRIPT FIVE
    ['₆'] = '_6', -- SUBSCRIPT SIX
    ['₇'] = '_7', -- SUBSCRIPT SEVEN
    ['₈'] = '_8', -- SUBSCRIPT EIGHT
    ['₉'] = '_9', -- SUBSCRIPT NINE
    ['₊'] = '', -- SUBSCRIPT PLUS SIGN
    ['₋'] = '', -- SUBSCRIPT MINUS
    ['₌'] = '', -- SUBSCRIPT EQUALS SIGN
    ['₍'] = '', -- SUBSCRIPT LEFT PARENTHESIS
    ['₎'] = '', -- SUBSCRIPT RIGHT PARENTHESIS
    ['€'] = 'eur', -- EURO SIGN
    ['℃'] = 'C', -- DEGREE CELSIUS
    ['№'] = 'No', -- NUMERO SIGN
    ['℗'] = '(P)', -- SOUND RECORDING COPYRIGHT
    ['℠'] = 'SM', -- SERVICE MARK
    ['™'] = 'TM', -- TRADE MARK SIGN
    ['Ω'] = 'Ohm', -- OHM SIGN
    ['℮'] = 'est', -- ESTIMATED SYMBOL
    ['←'] = '', -- LEFTWARDS ARROW
    ['↑'] = '', -- UPWARDS ARROW
    ['→'] = '', -- RIGHTWARDS ARROW
    ['↓'] = '', -- DOWNWARDS ARROW
    ['∞'] = 'inf', -- INFINITY
    ['⋕'] = '', -- EQUAL AND PARALLEL TO
    ['〈'] = '', -- LEFT-POINTING ANGLE BRACKET
    ['〉'] = '', -- RIGHT-POINTING ANGLE BRACKET
    ['␣'] = '', -- OPEN BOX
    ['◦'] = '', -- WHITE BULLET
    ['✁'] = '', -- UPPER BLADE SCISSORS
    --Derived accented characters
    ['À'] = 'A', -- LATIN CAPITAL LETTER A WITH GRAVE
    ['Á'] = "A", -- LATIN CAPITAL LETTER A WITH ACUTE
    ['Â'] = 'A', -- LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    ['Ã'] = 'A', -- LATIN CAPITAL LETTER A with TILDE
    ['Å'] = 'A', -- LATIN CAPITAL LETTER A with RING ABOVE
    ['Ä'] = 'A', -- LATIN CAPITAL LETTER A with DIAERESIS
    ['Ç'] = 'C', -- LATIN CAPITAL LETTER C with CEDILLA
    ['È'] = 'E', -- LATIN CAPITAL LETTER E with GRAVE
    ['É'] = 'E', -- LATIN CAPITAL LETTER E WITH ACUTE
    ['Ê'] = 'E', -- LATIN CAPITAL LETTER E with CIRCUMFLEX
    ['Ë'] = 'E', -- LATIN CAPITAL LETTER E with DIAERESIS
    ['Ì'] = 'I', -- LATIN CAPITAL LETTER I with GRAVE
    ['Í'] = 'I', -- LATIN CAPITAL LETTER I WITH ACUTE
    ['Î'] = 'I', -- LATIN CAPITAL LETTER I with CIRCUMFLEX
    ['Ï'] = 'I', -- LATIN CAPITAL LETTER I with DIAERESIS
    ['Ñ'] = 'N', -- LATIN CAPITAL LETTER N with TILDE
    ['Ò'] = 'O', -- LATIN CAPITAL LETTER O with GRAVE
    ['Ó'] = 'O', -- LATIN CAPITAL LETTER O WITH ACUTE
    ['Ô'] = 'O', -- LATIN CAPITAL LETTER O with CIRCUMFLEX
    ['Õ'] = 'O', -- LATIN CAPITAL LETTER O with TILDE
    ['Ö'] = 'O', -- LATIN CAPITAL LETTER O with DIAERESIS
    ['Ù'] = 'U', -- LATIN CAPITAL LETTER U with GRAVE
    ['Ú'] = 'U', -- LATIN CAPITAL LETTER U WITH ACUTE
    ['Û'] = 'U', -- LATIN CAPITAL LETTER U with CIRCUMFLEX
    ['Ü'] = 'U', -- LATIN CAPITAL LETTER U with DIAERESIS
    ['Ý'] = 'Y', -- LATIN CAPITAL LETTER Y WITH ACUTE
    ['à'] = 'a', -- LATIN SMALL LETTER A WITH
    ['á'] = 'a', -- LATIN SMALL LETTER A WITH ACUTE
    ['â'] = 'a', -- LATIN SMALL LETTER A WITH
    ['ã'] = 'a', -- LATIN SMALL LETTER A WITH
    ['ä'] = 'a', -- LATIN SMALL LETTER A WITH
    ['å'] = 'a', -- LATIN SMALL LETTER A WITH
    ['ç'] = 'c', -- LATIN SMALL LETTER C WITH
    ['è'] = 'e', -- LATIN SMALL LETTER E WITH
    ['é'] = 'e', -- LATIN SMALL LETTER E WITH ACUTE
    ['ê'] = 'e', -- LATIN SMALL LETTER E WITH
    ['ë'] = 'e', -- LATIN SMALL LETTER E WITH
    ['ì'] = 'i', -- LATIN SMALL LETTER I WITH
    ['í'] = 'i', -- LATIN SMALL LETTER I WITH ACUTE
    ['î'] = 'i', -- LATIN SMALL LETTER I WITH
    ['ï'] = 'i', -- LATIN SMALL LETTER I WITH
    ['ñ'] = 'n', -- LATIN SMALL LETTER N WITH
    ['ò'] = 'o', -- LATIN SMALL LETTER O WITH
    ['ó'] = 'o', -- LATIN SMALL LETTER O WITH ACUTE
    ['ô'] = 'o', -- LATIN SMALL LETTER O WITH
    ['õ'] = 'o', -- LATIN SMALL LETTER O WITH
    ['ö'] = 'o', -- LATIN SMALL LETTER O WITH
    ['ù'] = 'u', -- LATIN SMALL LETTER U WITH
    ['ú'] = 'u', -- LATIN SMALL LETTER U WITH ACUTE
    ['û'] = 'u', -- LATIN SMALL LETTER U WITH
    ['ü'] = 'u', -- LATIN SMALL LETTER U WITH
    ['ý'] = 'y', -- LATIN SMALL LETTER Y WITH ACUTE
    ['ÿ'] = 'y', -- LATIN SMALL LETTER Y WITH
    ['Ā'] = 'A', -- LATIN CAPITAL LETTER A with MACRON
    ['ā'] = 'a', -- LATIN SMALL LETTER A WITH
    ['Ă'] = 'A', -- LATIN CAPITAL LETTER A with BREVE
    ['ă'] = 'a', -- LATIN SMALL LETTER A WITH
    ['Ą'] = 'A', -- LATIN CAPITAL LETTER A with OGONEK
    ['ą'] = 'a', -- LATIN SMALL LETTER A WITH
    ['Ć'] = 'C', -- LATIN CAPITAL LETTER C WITH ACUTE
    ['ć'] = 'c', -- LATIN SMALL LETTER C WITH ACUTE
    ['Ĉ'] = 'C', -- LATIN CAPITAL LETTER C with CIRCUMFLEX
    ['ĉ'] = 'c', -- LATIN SMALL LETTER C WITH
    ['Ċ'] = 'C', -- LATIN CAPITAL LETTER C with DOT ABOVE
    ['ċ'] = 'c', -- LATIN SMALL LETTER C WITH
    ['Č'] = 'C', -- LATIN CAPITAL LETTER C with CARON
    ['č'] = 'c', -- LATIN SMALL LETTER C WITH
    ['Ď'] = 'D', -- LATIN CAPITAL LETTER D with CARON
    ['ď'] = 'd', -- LATIN SMALL LETTER D WITH
    ['Ē'] = 'E', -- LATIN CAPITAL LETTER E with MACRON
    ['ē'] = 'e', -- LATIN SMALL LETTER E WITH
    ['Ĕ'] = 'E', -- LATIN CAPITAL LETTER E with BREVE
    ['ĕ'] = 'e', -- LATIN SMALL LETTER E WITH
    ['Ė'] = 'E', -- LATIN CAPITAL LETTER E with DOT ABOVE
    ['ė'] = 'e', -- LATIN SMALL LETTER E WITH
    ['Ę'] = 'E', -- LATIN CAPITAL LETTER E with OGONEK
    ['ę'] = 'e', -- LATIN SMALL LETTER E WITH
    ['Ě'] = 'E', -- LATIN CAPITAL LETTER E with CARON
    ['ě'] = 'e', -- LATIN SMALL LETTER E WITH
    ['Ĝ'] = 'G', -- LATIN CAPITAL LETTER G with CIRCUMFLEX
    ['ĝ'] = 'g', -- LATIN SMALL LETTER G WITH
    ['Ğ'] = 'G', -- LATIN CAPITAL LETTER G with BREVE
    ['ğ'] = 'g', -- LATIN SMALL LETTER G WITH
    ['Ġ'] = 'G', -- LATIN CAPITAL LETTER G with DOT ABOVE
    ['ġ'] = 'g', -- LATIN SMALL LETTER G WITH
    ['Ģ'] = 'G', -- LATIN CAPITAL LETTER G with CEDILLA
    ['ģ'] = 'g', -- LATIN SMALL LETTER G WITH
    ['Ĥ'] = 'H', -- LATIN CAPITAL LETTER H with CIRCUMFLEX
    ['ĥ'] = 'h', -- LATIN SMALL LETTER H WITH
    ['Ĩ'] = 'I', -- LATIN CAPITAL LETTER I with TILDE
    ['ĩ'] = 'i', -- LATIN SMALL LETTER I WITH
    ['Ī'] = 'I', -- LATIN CAPITAL LETTER I with MACRON
    ['Ĭ'] = 'I', -- LATIN CAPITAL LETTER I with BREVE
    ['ĭ'] = 'i', -- LATIN SMALL LETTER I WITH
    ['Į'] = 'I', -- LATIN CAPITAL LETTER I with OGONEK
    ['į'] = 'i', -- LATIN SMALL LETTER I WITH
    ['İ'] = 'I', -- LATIN CAPITAL LETTER I with DOT ABOVE
    ['Ĵ'] = 'J', -- LATIN CAPITAL LETTER J with CIRCUMFLEX
    ['ĵ'] = 'j', -- LATIN SMALL LETTER J WITH
    ['Ķ'] = 'K', -- LATIN CAPITAL LETTER K with CEDILLA
    ['ķ'] = 'k', -- LATIN SMALL LETTER K WITH
    ['Ĺ'] = 'L', -- LATIN CAPITAL LETTER L WITH ACUTE
    ['ĺ'] = 'l', -- LATIN SMALL LETTER L WITH ACUTE
    ['Ļ'] = 'L', -- LATIN CAPITAL LETTER L with CEDILLA
    ['ļ'] = 'l', -- LATIN SMALL LETTER L WITH
    ['Ľ'] = 'L', -- LATIN CAPITAL LETTER L with CARON
    ['ľ'] = 'l', -- LATIN SMALL LETTER L WITH
    ['Ł'] = '', --LATIN CAPITAL LETTER L WITH STROKE
    ['ł'] = '', --LATIN SMALL LETTER L WITH STROKE
    ['Ń'] = 'N', -- LATIN CAPITAL LETTER N WITH ACUTE
    ['ń'] = 'n', -- LATIN SMALL LETTER N WITH ACUTE
    ['Ņ'] = 'N', -- LATIN CAPITAL LETTER N with CEDILLA
    ['ņ'] = 'n', -- LATIN SMALL LETTER N WITH
    ['Ň'] = 'N', -- LATIN CAPITAL LETTER N with CARON
    ['ň'] = 'n', -- LATIN SMALL LETTER N WITH
    ['Ō'] = 'O', -- LATIN CAPITAL LETTER O with MACRON
    ['ō'] = 'o', -- LATIN SMALL LETTER O WITH
    ['Ŏ'] = 'O', -- LATIN CAPITAL LETTER O with BREVE
    ['ŏ'] = 'o', -- LATIN SMALL LETTER O WITH
    ['Ő'] = 'O', -- LATIN CAPITAL LETTER O with DOUBLE ACUTE
    ['ő'] = 'o', -- LATIN SMALL LETTER O WITH
    ['Ŕ'] = 'R', -- LATIN CAPITAL LETTER R WITH ACUTE
    ['ŕ'] = 'r', -- LATIN SMALL LETTER R WITH ACUTE
    ['Ŗ'] = 'R', -- LATIN CAPITAL LETTER R with CEDILLA
    ['ŗ'] = 'r', -- LATIN SMALL LETTER R WITH
    ['Ř'] = 'R', -- LATIN CAPITAL LETTER R with CARON
    ['ř'] = 'r', -- LATIN SMALL LETTER R WITH
    ['Ś'] = 'S', -- LATIN CAPITAL LETTER S WITH ACUTE
    ['ś'] = 's', -- LATIN SMALL LETTER S WITH ACUTE
    ['Ŝ'] = 'S', -- LATIN CAPITAL LETTER S with CIRCUMFLEX
    ['ŝ'] = 's', -- LATIN SMALL LETTER S WITH
    ['Ş'] = 'S', -- LATIN CAPITAL LETTER S with CEDILLA
    ['ş'] = 's', -- LATIN SMALL LETTER S WITH
    ['Š'] = 'S', -- LATIN CAPITAL LETTER S with CARON
    ['š'] = 's', -- LATIN SMALL LETTER S WITH
    ['Ţ'] = 'T', -- LATIN CAPITAL LETTER T with CEDILLA
    ['ţ'] = 't', -- LATIN SMALL LETTER T WITH
    ['Ť'] = 'T', -- LATIN CAPITAL LETTER T with CARON
    ['ť'] = 't', -- LATIN SMALL LETTER T WITH
    ['Ũ'] = 'U', -- LATIN CAPITAL LETTER U with TILDE
    ['ũ'] = 'u', -- LATIN SMALL LETTER U WITH
    ['Ū'] = 'U', -- LATIN CAPITAL LETTER U with MACRON
    ['ū'] = 'u', -- LATIN SMALL LETTER U WITH
    ['Ŭ'] = 'U', -- LATIN CAPITAL LETTER U with BREVE
    ['ŭ'] = 'u', -- LATIN SMALL LETTER U WITH
    ['Ů'] = 'U', -- LATIN CAPITAL LETTER U with RING ABOVE
    ['ů'] = 'u', -- LATIN SMALL LETTER U WITH
    ['Ű'] = 'U', -- LATIN CAPITAL LETTER U with DOUBLE ACUTE
    ['ű'] = 'u', -- LATIN SMALL LETTER U WITH
    ['Ų'] = 'U', -- LATIN CAPITAL LETTER U with OGONEK
    ['ų'] = 'u', -- LATIN SMALL LETTER U WITH
    ['Ŵ'] = 'W', -- LATIN CAPITAL LETTER W with CIRCUMFLEX
    ['ŵ'] = 'w', -- LATIN SMALL LETTER W WITH
    ['Ŷ'] = 'Y', -- LATIN CAPITAL LETTER Y with CIRCUMFLEX
    ['ŷ'] = 'y', -- LATIN SMALL LETTER Y WITH
    ['Ÿ'] = 'Y', -- LATIN CAPITAL LETTER Y with DIAERESIS
    ['Ź'] = 'Z', -- LATIN CAPITAL LETTER Z WITH ACUTE
    ['ź'] = 'z', -- LATIN SMALL LETTER Z WITH ACUTE
    ['Ż'] = 'Z', -- LATIN CAPITAL LETTER Z with DOT ABOVE
    ['ż'] = 'z', -- LATIN SMALL LETTER Z WITH
    ['Ž'] = 'Z', -- LATIN CAPITAL LETTER Z with CARON
    ['ž'] = 'z', -- LATIN SMALL LETTER Z WITH
    ['Ǎ'] = 'A', -- LATIN CAPITAL LETTER A with CARON
    ['ǎ'] = 'a', -- LATIN SMALL LETTER A WITH
    ['Ǐ'] = 'I', -- LATIN CAPITAL LETTER I with CARON
    ['ǐ'] = 'i', -- LATIN SMALL LETTER I WITH
    ['Ǒ'] = 'O', -- LATIN CAPITAL LETTER O with CARON
    ['ǒ'] = 'o', -- LATIN SMALL LETTER O WITH
    ['Ǔ'] = 'U', -- LATIN CAPITAL LETTER U with CARON
    ['ǔ'] = 'u', -- LATIN SMALL LETTER U WITH
    ['Ǧ'] = 'G', -- LATIN CAPITAL LETTER G with CARON
    ['ǧ'] = 'g', -- LATIN SMALL LETTER G WITH
    ['Ǩ'] = 'K', -- LATIN CAPITAL LETTER K with CARON
    ['ǩ'] = 'k', -- LATIN SMALL LETTER K WITH
    ['Ǫ'] = 'O', -- LATIN CAPITAL LETTER O with OGONEK
    ['ǫ'] = 'o', -- LATIN SMALL LETTER O WITH
    ['ǰ'] = 'j', -- LATIN SMALL LETTER J WITH
    ['Ǵ'] = 'G', -- LATIN CAPITAL LETTER G WITH ACUTE
    ['ǵ'] = 'g', -- LATIN SMALL LETTER G WITH ACUTE
    ['Ḃ'] = 'B', -- LATIN CAPITAL LETTER B with DOT ABOVE
    ['ḃ'] = 'b', -- LATIN SMALL LETTER B WITH
    ['Ḅ'] = 'B', -- LATIN CAPITAL LETTER B with DOT BELOW
    ['ḅ'] = 'b', -- LATIN SMALL LETTER B WITH
    ['Ḇ'] = 'B', -- LATIN CAPITAL LETTER B with LINE BELOW
    ['ḇ'] = 'b', -- LATIN SMALL LETTER B WITH
    ['Ḋ'] = 'D', -- LATIN CAPITAL LETTER D with DOT ABOVE
    ['ḋ'] = 'd', -- LATIN SMALL LETTER D WITH
    ['Ḍ'] = 'D', -- LATIN CAPITAL LETTER D with DOT BELOW
    ['ḍ'] = 'd', -- LATIN SMALL LETTER D WITH
    ['Ḏ'] = 'D', -- LATIN CAPITAL LETTER D with LINE BELOW
    ['ḏ'] = 'd', -- LATIN SMALL LETTER D WITH
    ['Ḑ'] = 'D', -- LATIN CAPITAL LETTER D with CEDILLA
    ['ḑ'] = 'd', -- LATIN SMALL LETTER D WITH
    ['Ḟ'] = 'F', -- LATIN CAPITAL LETTER F with DOT ABOVE
    ['ḟ'] = 'f', -- LATIN SMALL LETTER F WITH
    ['Ḡ'] = 'G', -- LATIN CAPITAL LETTER G with MACRON
    ['ḡ'] = 'g', -- LATIN SMALL LETTER G WITH
    ['Ḣ'] = 'H', -- LATIN CAPITAL LETTER H with DOT ABOVE
    ['ḣ'] = 'h', -- LATIN SMALL LETTER H WITH
    ['Ḥ'] = 'H', -- LATIN CAPITAL LETTER H with DOT BELOW
    ['ḥ'] = 'h', -- LATIN SMALL LETTER H WITH
    ['Ḧ'] = 'H', -- LATIN CAPITAL LETTER H with DIAERESIS
    ['ḧ'] = 'h', -- LATIN SMALL LETTER H WITH
    ['Ḩ'] = 'H', -- LATIN CAPITAL LETTER H with CEDILLA
    ['ḩ'] = 'h', -- LATIN SMALL LETTER H WITH
    ['Ḱ'] = 'K', -- LATIN CAPITAL LETTER K WITH ACUTE
    ['ḱ'] = 'k', -- LATIN SMALL LETTER K WITH ACUTE
    ['Ḳ'] = 'K', -- LATIN CAPITAL LETTER K with DOT BELOW
    ['ḳ'] = 'k', -- LATIN SMALL LETTER K WITH
    ['Ḵ'] = 'K', -- LATIN CAPITAL LETTER K with LINE BELOW
    ['ḵ'] = 'k', -- LATIN SMALL LETTER K WITH
    ['Ḷ'] = 'L', -- LATIN CAPITAL LETTER L with DOT BELOW
    ['ḷ'] = 'l', -- LATIN SMALL LETTER L WITH
    ['Ḻ'] = 'L', -- LATIN CAPITAL LETTER L with LINE BELOW
    ['ḻ'] = 'l', -- LATIN SMALL LETTER L WITH
    ['Ḿ'] = 'M', -- LATIN CAPITAL LETTER M WITH ACUTE
    ['ḿ'] = 'm', -- LATIN SMALL LETTER M WITH ACUTE
    ['Ṁ'] = 'M', -- LATIN CAPITAL LETTER M with DOT ABOVE
    ['ṁ'] = 'm', -- LATIN SMALL LETTER M WITH
    ['Ṃ'] = 'M', -- LATIN CAPITAL LETTER M with DOT BELOW
    ['ṃ'] = 'm', -- LATIN SMALL LETTER M WITH
    ['Ṅ'] = 'N', -- LATIN CAPITAL LETTER N with DOT ABOVE
    ['ṅ'] = 'n', -- LATIN SMALL LETTER N WITH
    ['Ṇ'] = 'N', -- LATIN CAPITAL LETTER N with DOT BELOW
    ['ṇ'] = 'n', -- LATIN SMALL LETTER N WITH
    ['Ṉ'] = 'N', -- LATIN CAPITAL LETTER N with LINE BELOW
    ['ṉ'] = 'n', -- LATIN SMALL LETTER N WITH
    ['Ṕ'] = 'P', -- LATIN CAPITAL LETTER P WITH ACUTE
    ['ṕ'] = 'p', -- LATIN SMALL LETTER P WITH ACUTE
    ['Ṗ'] = 'P', -- LATIN CAPITAL LETTER P with DOT ABOVE
    ['ṗ'] = 'p', -- LATIN SMALL LETTER P WITH
    ['Ṙ'] = 'R', -- LATIN CAPITAL LETTER R with DOT ABOVE
    ['ṙ'] = 'r', -- LATIN SMALL LETTER R WITH
    ['Ṛ'] = 'R', -- LATIN CAPITAL LETTER R with DOT BELOW
    ['ṛ'] = 'r', -- LATIN SMALL LETTER R WITH
    ['Ṟ'] = 'R', -- LATIN CAPITAL LETTER R with LINE BELOW
    ['ṟ'] = 'r', -- LATIN SMALL LETTER R WITH
    ['Ṡ'] = 'S', -- LATIN CAPITAL LETTER S with DOT ABOVE
    ['ṡ'] = 's', -- LATIN SMALL LETTER S WITH
    ['Ṣ'] = 'S', -- LATIN CAPITAL LETTER S with DOT BELOW
    ['ṣ'] = 's', -- LATIN SMALL LETTER S WITH
    ['Ṫ'] = 'T', -- LATIN CAPITAL LETTER T with DOT ABOVE
    ['ṫ'] = 't', -- LATIN SMALL LETTER T WITH
    ['Ṭ'] = 'T', -- LATIN CAPITAL LETTER T with DOT BELOW
    ['ṭ'] = 't', -- LATIN SMALL LETTER T WITH
    ['Ṯ'] = 'T', -- LATIN CAPITAL LETTER T with LINE BELOW
    ['ṯ'] = 't', -- LATIN SMALL LETTER T WITH
    ['Ṽ'] = 'V', -- LATIN CAPITAL LETTER V with TILDE
    ['ṽ'] = 'v', -- LATIN SMALL LETTER V WITH
    ['Ṿ'] = 'V', -- LATIN CAPITAL LETTER V with DOT BELOW
    ['ṿ'] = 'v', -- LATIN SMALL LETTER V WITH
    ['Ẁ'] = 'W', -- LATIN CAPITAL LETTER W with GRAVE
    ['ẁ'] = 'w', -- LATIN SMALL LETTER W WITH
    ['Ẃ'] = 'W', -- LATIN CAPITAL LETTER W WITH ACUTE
    ['ẃ'] = 'w', -- LATIN SMALL LETTER W WITH ACUTE
    ['Ẅ'] = 'W', -- LATIN CAPITAL LETTER W with DIAERESIS
    ['ẅ'] = 'w', -- LATIN SMALL LETTER W WITH
    ['Ẇ'] = 'W', -- LATIN CAPITAL LETTER W with DOT ABOVE
    ['ẇ'] = 'w', -- LATIN SMALL LETTER W WITH
    ['Ẉ'] = 'W', -- LATIN CAPITAL LETTER W with DOT BELOW
    ['ẉ'] = 'w', -- LATIN SMALL LETTER W WITH
    ['Ẋ'] = 'X', -- LATIN CAPITAL LETTER X with DOT ABOVE
    ['ẋ'] = 'x', -- LATIN SMALL LETTER X WITH
    ['Ẍ'] = 'X', -- LATIN CAPITAL LETTER X with DIAERESIS
    ['ẍ'] = 'x', -- LATIN SMALL LETTER X WITH
    ['Ẏ'] = 'Y', -- LATIN CAPITAL LETTER Y with DOT ABOVE
    ['ẏ'] = 'y', -- LATIN SMALL LETTER Y WITH
    ['Ẑ'] = 'Z', -- LATIN CAPITAL LETTER Z with CIRCUMFLEX
    ['ẑ'] = 'z', -- LATIN SMALL LETTER Z WITH
    ['Ẓ'] = 'Z', -- LATIN CAPITAL LETTER Z with DOT BELOW
    ['ẓ'] = 'z', -- LATIN SMALL LETTER Z WITH
    ['Ẕ'] = 'Z', -- LATIN CAPITAL LETTER Z with LINE BELOW
    ['ẕ'] = 'z', -- LATIN SMALL LETTER Z WITH
    ['ẖ'] = 'h', -- LATIN SMALL LETTER H WITH
    ['ẗ'] = 't', -- LATIN SMALL LETTER T WITH
    ['ẘ'] = 'w', -- LATIN SMALL LETTER W WITH
    ['ẙ'] = 'y', -- LATIN SMALL LETTER Y WITH
    ['Ạ'] = 'A', -- LATIN CAPITAL LETTER A with DOT BELOW
    ['ạ'] = 'a', -- LATIN SMALL LETTER A WITH
    ['Ẹ'] = 'E', -- LATIN CAPITAL LETTER E with DOT BELOW
    ['ẹ'] = 'e', -- LATIN SMALL LETTER E WITH
    ['Ẽ'] = 'E', -- LATIN CAPITAL LETTER E with TILDE
    ['ẽ'] = 'e', -- LATIN SMALL LETTER E WITH
    ['Ị'] = 'I', -- LATIN CAPITAL LETTER I with DOT BELOW
    ['ị'] = 'i', -- LATIN SMALL LETTER I WITH
    ['Ọ'] = 'O', -- LATIN CAPITAL LETTER O with DOT BELOW
    ['ọ'] = 'o', -- LATIN SMALL LETTER O WITH
    ['Ụ'] = 'U', -- LATIN CAPITAL LETTER U with DOT BELOW
    ['ụ'] = 'u', -- LATIN SMALL LETTER U WITH
    ['Ỳ'] = 'Y', -- LATIN CAPITAL LETTER Y with GRAVE
    ['ỳ'] = 'y', -- LATIN SMALL LETTER Y WITH
    ['Ỵ'] = 'Y', -- LATIN CAPITAL LETTER Y with DOT BELOW
    ['ỵ'] = 'y', -- LATIN SMALL LETTER Y WITH
    ['Ỹ'] = 'Y', -- LATIN CAPITAL LETTER Y with TILDE
    ['ỹ'] = 'y', -- LATIN SMALL LETTER Y WITH
  }
  for k, v in pairs(mappingTable) do
    str = str:gsub(k, v)
  end
  return str
end


return M
